# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "model3app_vm"
    v.memory = 1024
  end

  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.ssh.forward_agent = true

  config.vm.network "private_network", ip: "10.11.12.100"
  config.vm.synced_folder "./..", "/model3app", type: "nfs", nfs: true

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["../chef/cookbooks", "cookbooks"]
    chef.add_recipe :apt
    chef.add_recipe 'apache2'
    chef.add_recipe 'apache2::mod_php5'
    chef.add_recipe 'composer'
    chef.add_recipe 'git'
    chef.add_recipe 'mysql::server'
    chef.add_recipe 'vim'
    chef.add_recipe 'php'
    chef.add_recipe 'php::module_mysql'
    chef.add_recipe 'chef-php-extra::module_mcrypt'
    chef.add_recipe 'chef-php-extra::development'
    chef.add_recipe 'model3app'
    chef.json = {
      :apache => {
        :default_site_enabled => "true",
        :run_dir              => "/var/run/apache2",
        :dir                  => "/etc/apache2",
        :log_dir              => "/var/log/apache2",
        :lock_dir             => "/var/lock/apache2",
        :error_log            => "error.log",
        :user                 => "www-data",
        :group                => "www-data",
        :binary               => "/usr/sbin/apache2",
        :cache_dir            => "/var/cache/apache2",
        :pid_file             => "/var/run/apache2/apache2.pid",
        :lib_dir              => "/usr/lib/apache2",
        :listen_ports         => [
          "80",
	      "443"
        ],
        :contact              => "ops@example.com",
        :timeout              => "300",
        :keepalive            => "On",
        :keepaliverequests    => "100",
        :keepalivetimeout     => "5"
      },
      :git    => {
        :prefix => "/usr/local"
      },
      :mysql  => {
        :server_root_password   => "password",
        :server_repl_password   => "password",
        :server_debian_password => "password",
        :service_name           => "mysql",
        :basedir                => "/usr",
        :data_dir               => "/var/lib/mysql",
        :root_group             => "root",
        :mysqladmin_bin         => "/usr/bin/mysqladmin",
        :mysql_bin              => "/usr/bin/mysql",
        :conf_dir               => "/etc/mysql",
        :confd_dir              => "/etc/mysql/conf.d",
        :socket                 => "/var/run/mysqld/mysqld.sock",
        :pid_file               => "/var/run/mysqld/mysqld.pid",
        :grants_path            => "/etc/mysql/grants.sql",
        :bind_address           => "0.0.0.0"
      },
      :php  => {
        :ext_conf_dir           => '/etc/php5/apache2/conf.d'
      }
    }
  end
  
end

